on:
  pull_request:
    branches:
      - master

name: pytests
jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.8, 3.9 ]
    steps:
      - uses: 8BitJonny/gh-get-current-pr@2.0.0
        id: PR
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # Verbose setting SHA when using Pull_Request event trigger to fix #16
          sha: ${{ github.event.pull_request.head.sha }}
          # Only return if PR is still open
          filterOutClosed: true
          # Only return if PR is not in draft state
          filterOutDraft: 1

      - name: Check PR message
        id: check
        if: success() && steps.PR.outputs.number
        run: |
          message=$(echo ${{ steps.PR.outputs.pr_body }})
          echo "Message is $message"
          if [[ "$message" == "" ]] ; then
            echo "Pull request message not provided!!"
            exit 1
          fi
          if [[ "$message" != *"!minor" ]] && [[ "$message" != *"!wip" ]] && [[ "$message" != *"!WIP" ]] && [[ "$message" != "doc:"* ]] ; then
            echo "::set-output name=run::true"
          else
            echo "skipping pytests"
            echo "::set-output name=run::false"
          fi

      - uses: actions/checkout@master
        if: steps.check.outputs.run == 'true'
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
          ref: refs/heads/${{ github.head_ref }}

      - name: Set up Python ${{ matrix.python-version }}
        if: steps.check.outputs.run == 'true'
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        if: steps.check.outputs.run == 'true'
        run: |
          python -m pip install --upgrade pip
          pip install wheel
          pip install pytest
          pip install pytest-gitignore
          pip install pytest-github-actions-annotate-failures
          pip install .

      - name: Test with pytest
        if: steps.check.outputs.run == 'true'
        run: |
          pytest -s -v
