on:
  pull_request:
    branches:
      - master

name: pytests
jobs:
  pytest:
    runs-on: ubuntu-latest
    if: "
      !endsWith(github.event.head_commit.message, '!minor')
      && !endsWith(github.event.head_commit.message, '!wip')
      && !endsWith(github.event.head_commit.message, '!WIP')
      && !startsWith(github.event.head_commit.message, 'doc:')
    "
    strategy:
      matrix:
        python-version: [ 3.8, 3.9 ]
    steps:
      - name: Get PR Commits
        id: 'get-pr-commits'
        uses: tim-actions/get-pr-commits@master
        with:
          token: ${{ secrets.ORG_TOKEN_CICD }}

      - name: Check content
        run: |
          echo ${{ steps.get-pr-commits.outputs.commits }}

      - uses: actions/checkout@master
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
          ref: refs/heads/${{ github.head_ref }}

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel
          pip install pytest
          pip install pytest-gitignore
          pip install pytest-github-actions-annotate-failures
          pip install .

      - name: Test with pytest
        run: |
          pytest -s -v
